### ISSUE TITLE
.predict does not work.

### ISSUE THREAD

**Issue by kkp15** [maxrmorrison/torchcrepe#10]
Hello! Thank you for your contribution :)

I was going to simply test the torchcrepe.predict() but it won't work.
The code is simple as below.
I installed the torchcrepe using pip.

audio, sr = torchcrepe.load.audio(path)

frame_rate = num_frames / (len(audio)/sr)
crepe_step_size = 1000 / frame_rate  # milliseconds
fmin = 50
fmax = 550

model = 'full'

device = 'cuda:0'

batch_size = 1

pitch, harmonicity = torchcrepe.predict(audio,
                        sr,
                        crepe_step_size,
                        fmin,
                        fmax,
                        model,
                        batch_size=batch_size,
                        device=device,
                        decoder=torchcrepe.decode.viterbi,
                        `return_harmonicity=True)`

TypeError: predict() got an unexpected keyword argument 'device'

Is this error expected to happen?

**Comment by maxrmorrison** [comment]
The GitHub repo was a few commits ahead of PyPi. The `device` parameter was added in fd8325 to allow for processing audio signals larger than GPU memory. I just synced PyPi with the current commit, so reinstall, make sure you have version 0.0.12, and it should work. The README corresponding to the current PyPi version can always be found at https://pypi.org/project/torchcrepe/.
