### ISSUE TITLE
Using Weighted Argmax Local Average decoding results in RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by ben-hayes** [maxrmorrison/torchcrepe#11]
Using PyPI release v0.0.12, calling `.predict` with `decoder=torchcrepe.decode.weighted_argmax` results in the following error:

```RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Loops.cuh":94, please report a bug to PyTorch.```

This issue on the PyTorch repo (https://github.com/pytorch/pytorch/issues/48393) suggests this is because of a bug preventing tensors from being compared to scalar tensors on a different device. This may be fixed in a later release, but for now it may be best to simply instantiate scalar tensors on the same device as the input.

The problematic lines are: https://github.com/maxrmorrison/torchcrepe/blob/a921d9daf8a9f34f4791e0312cd4c702a56d611a/torchcrepe/decode.py#L27-L28

If it's okay with you, I'll submit a small PR to address this until the issue is resolved in core PyTorch.

**Comment by ben-hayes** [comment]
Thanks for the fantastic work, by the way. This port is proving very useful :)

**Comment by maxrmorrison** [comment]
Thanks! Glad it's proved useful. I just confirmed the issue on my machine. I'll take a look at the PR now.

**Comment by maxrmorrison** [comment]
Merged in #12
