### ISSUE TITLE
Same input, same params, different output

### ISSUE THREAD

**Issue by jwang44** [maxrmorrison/torchcrepe#16]
Issue: The model would produce different results for the same input. 
To reproduce:
```python
import torch, torchcrepe

audio = torch.rand([1, 10000])
pitch_0 = torchcrepe.predict(audio=audio, sample_rate=16000, model='tiny')
pitch_1 = torchcrepe.predict(audio=audio, sample_rate=16000, model='tiny')
torch.equal(pitch_0, pitch_1)
```
Expected behaviour: The above code should return `True`.
Actual behaviour: It returns `False`, indicating that `pitch_0` and `pitch_1` have different values. 

Is there a way to make sure that the model returns consistent results across multiple runs?

**Comment by maxrmorrison** [comment]
You can remove the dithering to get something deterministic--but with quantization error. I prefer the noise to quantization error for most downstream tasks I use this for.
