### ISSUE TITLE
Rewrite median and mean pooling to achieve 5x faster

### ISSUE THREAD

**Issue by leng-yue** [maxrmorrison/torchcrepe#21]
After profiling, I found that the current implementation of mean and median pooling is extremely slow (python loops). And they consumed most of their time in crepe inference. Thus, I rewrote them in torch and accelerated these two functions by *1000x*. Overall, it can improve the inference speed of crepe full to 5x of the original speed.

The rewrited pooling and test cases can be found here: https://github.com/fishaudio/fish-diffusion/commit/f03014f17e250e6597d5da22593478a30d470826

I would like to make a PR to torchcrepe if torchcrepe wants to adapt this optimization.

**Comment by maxrmorrison** [comment]
Yeah, I'd be happy to test a pull request for that. That would be great. I assume that this improves performance for GPU and not CPU, so just make sure to only apply it to GPU so it doesn't negatively impact CPU performance.

**Comment by leng-yue** [comment]
It improves CPU performance by utilizing Torch's operations (based on C and C++) instead of Python loops in the current implementation. I will submit a pull request later.

**Comment by leng-yue** [comment]
Any update?

**Comment by maxrmorrison** [comment]
The speedup and tests look great. Merged and deployed in 0.0.19. Thanks!
