### ISSUE TITLE
traceback when using median filter

### ISSUE THREAD

**Issue by RVC-Boss** [maxrmorrison/torchcrepe#23]
pytorch version: 1.10.0
torchcrepe version: 0.0.19

  File "/root/miniconda3/lib/python3.9/site-packages/torchcrepe/filter.py", line 90, in median
    x_masked = torch.where(mask.bool(), x, float("inf"))
RuntimeError: expected scalar type float but found double

(Pdb) x.dtype
torch.float32

pd = torchcrepe.filter.median(pd, 3)
pd.dtype is float32

I made a pr to fix it.

**Comment by RVC-Boss** [comment]
I created another pr to fix it @maxrmorrison

**Comment by maxrmorrison** [comment]
Thanks for the fix! Merged and deployed in version 0.0.20.
