### ISSUE TITLE
Getting the time, frequency, confidence, activation like original crepe

### ISSUE THREAD

**Issue by rakuri255** [maxrmorrison/torchcrepe#26]
Is it possible to get the same data as the [original crepe](https://github.com/marl/crepe)?

time, frequency, confidence, activation = crepe.predict(audio, sr, viterbi=True)

**Comment by maxrmorrison** [comment]
`time` is just the time corresponding to the center of each frame, so you can get that with `linspace`. For the activation, you can use [this function](https://github.com/maxrmorrison/torchcrepe/blob/13ad40ff9c5263d4c9c827722a04384f629bf430/torchcrepe/core.py#L49) but remove the postprocessing step.
