### ISSUE TITLE
Plotting results? How to do it best?

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [maxrmorrison/torchcrepe#37]
Hi,

is there a way to plot the results? I have tried some things already but it seems like everyone does it differently.
Any hints where to start?

**Comment by maxrmorrison** [comment]
There's no "best" way, really. It depends what you need to visualize for your purposes. Here's a few possibilities:

### Plot aligned pitch and periodicity

 ```
figure, axes = plt.subplots(2, 1)
axes[0].plot(pitch.squeeze())
axes[1].plot(periodicity.squeeze())
figure.show()
```
![image](https://github.com/maxrmorrison/torchcrepe/assets/42818349/8596e01a-5713-4e96-b5bc-af20bb0117b7)

### Plot only pitch in periodic regions
```
figure, axis = plt.subplots(1, 1)
THRESHOLD = 0.1625
voiced = pitch.clone()
voiced[periodicity < THRESHOLD] = float('nan')
axis.plot(voiced.squeeze())
axis.set_xlim(0, voiced.shape[-1])
figure.show()
```
![image](https://github.com/maxrmorrison/torchcrepe/assets/42818349/c73ef78a-d3d5-4bde-9f44-09d8a0e3d705)


### Plot pitch with color determined by periodicity
```
figure, axis = plt.subplots(1, 1)
sample_rate = 22050
hopsize = 256
seconds = pitch.shape[-1] * hopsize / sample_rate
upsampled_pitch = 2 ** torch.nn.functional.interpolate(
    torch.log2(pitch)[None],
    scale_factor=10,
    mode='linear')[0]
upsampled_periodicity = torch.nn.functional.interpolate(
    periodicity[None],
    scale_factor=10,
    mode='linear')[0]
axis.scatter(
    torch.linspace(0., seconds, upsampled_pitch.shape[-1]),
    upsampled_pitch.squeeze(),
    c=matplotlib.cm.RdYlGn(upsampled_periodicity[0] / upsampled_periodicity.max()), edgecolor='none')
figure.show()
```
![image](https://github.com/maxrmorrison/torchcrepe/assets/42818349/73e132d4-2627-437c-8e16-a7ab307ad334)
