### ISSUE TITLE
torchcrepe.preprocess returns 'generator' object

### ISSUE THREAD

**Issue by ToraRuka** [maxrmorrison/torchcrepe#7]
First of all, I really appreciate for your great repo.

During I followed your instructions, I got some error with torchcrepe.preprocess()
What I've done is ,

```python
import torch
import torchcrepe
audio = torch.rand([1,22050])
torchcrepe.infer(torchcrepe.preprocess(audio, 22050, 256))
```

And it raised following error
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jg623/miniconda3/envs/pwgvc/lib/python3.6/site-packages/torchcrepe/core.py", line 439, in infer
    torchcrepe.load.model(frames.device, model)
AttributeError: 'generator' object has no attribute 'device'
```

Did I something wrong with torchcrepe?

In addition, do you have any plan to add batch-wised functions? (i.e. [#batch, #audiosample] to [#batch, #f0s] )

**Comment by maxrmorrison** [comment]
Try `next(torchcrepe.preprocess(...))` to get the result. `preprocess` returns a generator exactly for the reason of handling batching. Crepe batches over frames (of size 1024) of the original audio signal, so batching already occurs if you pass in a long enough audio signal and set `batch_size` to a value other than `None`. You can tune this batch size to utilize all of GPU memory if you have long enough audio. For processing many audio files, you can concatenate into a longer audio file or use `predict_from_files_to_files`. The latter method will get slightly lower GPU throughput.
