### ISSUE TITLE
torchcrepe.threshold.At modifies inplace

### ISSUE THREAD

**Issue by mpariente** [maxrmorrison/torchcrepe#9]
`torchcrepe.threshold.At` modifies inplace, would it make sense to add a clone op at the beginning?

**Comment by maxrmorrison** [comment]
Thanks for pointing that out. Right now, `At` is in-place and `Hysteresis` is not. These should definitely have similar behavior. I think making none of the thresholding functions in-place would be the easiest for users. I added the clone op in 08321cd.
